//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabelaSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public Pessoa()
        {
            this.Tarefa = new HashSet<Tarefa>();
        }
    
        public int PESID { get; set; }
        public string NOME { get; set; }
    
        public virtual ICollection<Tarefa> Tarefa { get; set; }
    }
}
