//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TabelaSQL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefa
    {
        public int TARID { get; set; }
        public string TARDESCRICAO { get; set; }
        public System.DateTime TARDATA { get; set; }
        public bool TARFEITO { get; set; }
        public int PESID { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
