//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdsAlmoxarifado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLABORADOR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COLABORADOR()
        {
            this.SAIDA = new HashSet<SAIDA>();
        }
    
        public int COLID { get; set; }
        public string COLNOME { get; set; }
        public string COLCARGO { get; set; }
        public Nullable<int> AREID { get; set; }
    
        public virtual AREA AREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SAIDA> SAIDA { get; set; }
    }
}
