//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdsAlmoxarifado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUTO()
        {
            this.ITENSENTRADA = new HashSet<ITENSENTRADA>();
            this.ITENSSAIDA = new HashSet<ITENSSAIDA>();
        }
    
        public int PROID { get; set; }
        public string PRODESCRICAO { get; set; }
        public Nullable<int> PROMINIMO { get; set; }
        public Nullable<int> PROMAXIMO { get; set; }
        public Nullable<int> PROESTOQUE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITENSENTRADA> ITENSENTRADA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITENSSAIDA> ITENSSAIDA { get; set; }
    }
}
