//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TdsAlmoxarifado.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAIDA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAIDA()
        {
            this.ITENSSAIDA = new HashSet<ITENSSAIDA>();
        }
    
        public int SAIID { get; set; }
        public System.DateTime SAIDATA { get; set; }
        public string SAIOBSERVACAO { get; set; }
        public int COLID { get; set; }
    
        public virtual COLABORADOR COLABORADOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ITENSSAIDA> ITENSSAIDA { get; set; }
    }
}
