//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniCursos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colaborador
    {
        public int colid { get; set; }
        public string collogin { get; set; }
        public string colsenha { get; set; }
    }
}
