//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniCursos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplinas
    {
        public int DISID { get; set; }
        public string DISDESCRIACAO { get; set; }
        public Nullable<int> CURSOID { get; set; }
        public Nullable<int> DISCH { get; set; }
    
        public virtual Cursos Cursos { get; set; }
    }
}
