//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseProfessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.Disciplina = new HashSet<Disciplina>();
        }
    
        public int CURSOID { get; set; }
        public string CURSODESCRICAO { get; set; }
        public string CURSOCODHABILIDADE { get; set; }
        public string CURSOMODALIDADE { get; set; }
    
        public virtual ICollection<Disciplina> Disciplina { get; set; }
    }
}
