//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace baseProfessor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disciplina
    {
        public int DISID { get; set; }
        public string DISDESCRIACAO { get; set; }
        public Nullable<int> CURSOID { get; set; }
        public Nullable<int> DISCH { get; set; }
    
        public virtual Curso Curso { get; set; }
    }
}
