//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATtesla.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Veiculo
    {
        public int CODIGO { get; set; }
        public string DESCRICAO { get; set; }
        public int VALOR { get; set; }
        public int CODIGMODELO { get; set; }
    }
}
