use master
go 
create database TdsAlmoxarifado

go
use TdsAlmoxarifado

go 
--Select* from sys.tables
Create table AREA
( AREID int IDENTITY(1,1) PRIMARY KEY,
ARESDESCRICAO VARCHAR (100) NOT NULL)

go
insert area values('TI') 
insert area (ARESDESCRICAO)values('COZINHA') 

Select* from AREA

go
select areid, aresdescricao from AREA
select areid as 'codigo', ARESDESCRICAO 'Descriçao' from AREA

--ordem  crescente pelo campo de descriçao
select areid as 'codego' , ARESDESCRICAO 'Descriçao' from AREA
order by ARESDESCRICAO asc
--ordem  DEcrescente pelo campo de descriçao
select areid as 'codego' , ARESDESCRICAO 'Descriçao' from AREA
order by ARESDESCRICAO desc
--AGREGANDO DADOS
select count (areid) as  'Total de Registro' from AREA

--tABELA CALABORADOR

CreatE table COLABORADOR
( COLID INT IDENTITY (1,1) PRIMARY KEY,
COLNOME VARCHAR(100) NOT NULL,
 COLCARGO VARCHAR(100) NULL,
  AREID INT, FOREIGN KEY (AREID) REFERENCES AREA(AREID)
  )

  --INSERINDO DADOS
INSERT COLABORADOR VALUES ('REGIS',NULL,1) 
INSERT COLABORADOR (COLNOME,AREID) VALUES('BRENO',2)
INSERT COLABORADOR (COLNOME,AREID) VALUES('ADSON',1)

Select* from COLABORADOR

--ATUALIZARDADOS
UPDATE COLABORADOR
SET COLCARGO='TIO'

Select* from COLABORADOR
WHERE COLID=2

UPDATE COLABORADOR
SET COLCARGO = 'FAZENDEIRO'
WHERE COLID=2

--DELETAR
DELETE COLABORADOR
WHERE COLID=6 

-- TENTANDO APAGAR ARE QUE TEM COLABORADPR USANDO
DELETE AREA
WHERE AREID=2

--JOIN
SELECT C.COLID 'CODIGO',
       C.COLNOME 'NOME',
       C.COLCARGO 'CARGO',
       A.ARESDESCRICAO 'AREA'
FROM COLABORADOR C JOIN
     AREA A ON C.AREID=A.AREID

	 --MAIS TESTES
INSERT COLABORADOR(COLNOME,AREID)VALUES('RYANDRA',1)
INSERT COLABORADOR(COLNOME,AREID)VALUES('MARCUS',1)

--
SELECT AREID 'CODIGO AREA', COUNT(AREID) 'QUANTIDADE' FROM COLABORADOR
GROUP BY AREID
--
SELECT AREID 'CODIGO AREA', COUNT(AREID) 'QUANTIDADE' FROM COLABORADOR
GROUP BY AREID

--TABELA PRODUTO
Create table PRODUTO
( PROID INT PRIMARY KEY IDENTITY,
PRODESCRICAO VARCHAR(100) NOT NULL,
PROMINIMO INT DEFAULT 0 CHECK (PROMINIMO>=0),
PROMAXIMO INT DEFAULT 0 CHECK (PROMAXIMO>=0),
PROESTOQUE INT DEFAULT 0 CHECK (PROESTOQUE>=0)
)
GO
--DROP TABELA PRODUTO
SELECT*FROM  PRODUTO

INSERT PRODUTO (PRODESCRICAO) 
VALUES ('FEIJAO')

INSERT PRODUTO 
VALUES ('BANANA',0,100,10)

INSERT PRODUTO (PRODESCRICAO,PROMINIMO, PROMAXIMO,PROESTOQUE)
VALUES ('RATINHO',1,20,40)

--TABELA ENTRADA

CREATE TABLE ENTRADA(
  ENTID INT PRIMARY KEY IDENTITY(1,1),
  ENTDATA DATETIME NOT NULL,
  ENTORIGEM VARCHAR(100) DEFAULT 'PADRAO' NULL,
  ENTNUMERONOTA VARCHAR(100) NULL,
  ENTOBSERVACAO VARCHAR(1000)
)

SELECT * FROM ENTRADA

GO
Insert ENTRADA (ENTDATA,ENTORIGEM, ENTNUMERONOTA, ENTOBSERVACAO)
       VALUES ('2022-27-07', 'Padrão', '001454', 'Menos 1 para Jhonas. Anote ai Ryandra')
GO
Insert ENTRADA (ENTDATA,ENTORIGEM, ENTNUMERONOTA, ENTOBSERVACAO)
       VALUES ('2022-27-07', 'Padrão', '002555', 'A NOTA É MINHA')
GO
Insert ENTRADA (ENTDATA,ENTORIGEM, ENTNUMERONOTA, ENTOBSERVACAO)
       VALUES ('2022-27-06', 'Padrão', '002555', 'A NOTA É MINHA')
GO
Insert ENTRADA (ENTDATA,ENTORIGEM, ENTNUMERONOTA, ENTOBSERVACAO)
       VALUES ('2022-27-07', 'Padrão', '001454', 'Menos 1 para Jhonas. Anote ai Ryandra')
GO
Insert ENTRADA (ENTDATA,ENTORIGEM, ENTNUMERONOTA, ENTOBSERVACAO)
       VALUES ('2022-27-07', 'Padrão', '002555', 'A NOTA É MINHA')
GO
Insert ENTRADA (ENTDATA,ENTORIGEM, ENTNUMERONOTA, ENTOBSERVACAO)
       VALUES ('2022-27-06', 'Padrão', '002555', 'A NOTA É MINHA')
GO
Insert ENTRADA (ENTDATA,ENTORIGEM, ENTNUMERONOTA, ENTOBSERVACAO)
       VALUES ('2022-30-01', 'Padrão', '0024444', 'NOTA 4')


--notas depois de janeiro
select*from entrada where entdata>'2022-31-01 00:00:00.000'
--notas do mes de junho
select*from entrada where entdata>'2022-01-06' and  ENTDATA<-'2022-30-06'
--notas do mes de junho
select*from entrada where entdata BETWEEN '2022-01-06' and '2022-30-06'  --TA ESTRANHO--
---
select*from entrada where  MONTH(ENTDATA)=6 AND YEAR(ENTDATA)='2022'  --TA ESTRANHO TBM--

--NOTAS DO MES DE 2022
select*from entrada where YEAR(ENTDATA)='2022'  --TA ESTRANHO--
--SELECIONAR NOTAS QUE NA OBSERVACAO CONTENHA O NOME DE RYANDRA E DO ANO DE 2022
select*from entrada where  MONTH(ENTDATA)='2022' AND ENTOBSERVACAO like '%Ryandra%'

--selecionar todos quecomecem com a letra p
select*from entrada where ENTORIGEM like 'p%'

--tabela itens entrada
CREATE TABLE ITENSENTRADA(
  ITEID INT PRIMARY KEY IDENTITY(1,1),
  ITEQUANTIDADE INT NOT NULL CHECK (ITEQUANTIDADE>=0),
  ITEPRECO NUMERIC(18,2) CHECK (ITEPRECO>0)NOT NULL,
  ITETOTAL AS  ITEQUANTIDADE*ITEPRECO,
  ENTID INT NOT NULL,
  PROID INT NOT NULL,
  FOREIGN KEY (ENTID) REFERENCES ENTRADA(ENTID),
  FOREIGN KEY (PROID) REFERENCES PRODUTO(PROID)
  )
  SELECT * FROM ITENSENTRADA
   SELECT * FROM PRODUTO
    SELECT * FROM ENTRADA

  Insert ITENSENTRADA (ENTID,PROID, ITEQUANTIDADE, ITEPRECO)
       VALUES (2,1,10,9.50)
  Insert ITENSENTRADA (ENTID,PROID, ITEQUANTIDADE, ITEPRECO)
       VALUES (2,3,5,2.50)

select I.ITEID 'Numero Item',
 E.ENTDATA'Data', 
 P.PRODESCRICAO'Produto', 
 I.ITEQUANTIDADE'Quantidade', 
 I.ITEPRECO'Valor', 
 I.ITETOTAL'Total' 
 from ITENSENTRADA I 
JOIN ENTRADA E ON I.ITEID=E.ENTID
JOIN PRODUTO P ON I.PROID=P.PROID

--custo da nota de entrada numero 1
select count(i.iteid)'Qtd de Itens',sum(i.itetotal)'Total da Nota' from ITENSENTRADA i
 join ENTRADA E ON I.ENTID=E.ENTDATA
 WHERE I.ENTID=2

 CREATE TABLE SAIDA(
SAIID INT PRIMARY KEY IDENTITY(1,1),
SAIDATA DATETIME NOT NULL DEFAULT GETDATE(),
SAIOBSERVACAO VARCHAR (1000) NULL,
COLID INT NOT NULL,
FOREIGN  KEY (COLID) REFERENCES COLABORADOR(COLID)
)


Insert SAIDA(SAIDATA, SAIOBSERVACAO, COLID) VALUES ('2022-20-01',null,1)
Insert SAIDA( SAIOBSERVACAO, COLID) VALUES ('alguns itens quebrados',2)
Insert SAIDA (COLID) values (1)

 SELECT * FROM SAIDA

  CREATE TABLE ITENSSAIDA(
ITSID INT PRIMARY KEY IDENTITY(1,1),
ITSQUANTIDADE INT NOT NULL CHECK(ITSQUANTIDADE>0),
SAIID INT NOT NULL,
PROID INT NOT NULL,
FOREIGN  KEY (SAIID) REFERENCES SAIDA(SAIID),
FOREIGN  KEY (PROID) REFERENCES PRODUTO(PROID)
)

--TRIGGER
SELECT*FROM SAIDA
SELECT*FROM PRODUTO
SELECT*FROM ITENSSAIDA

INSERT ITENSSAIDA(ITSQUANTIDADE,SAIID,PROID)
VALUES(2,6,3)
GO 
INSERT ITENSSAIDA(ITSQUANTIDADE,SAIID,PROID)
VALUES(10,5,1)
GO
INSERT ITENSSAIDA(ITSQUANTIDADE,SAIID,PROID)
VALUES(2,2,2)


SELECT I.*, P.PRODESCRICAO, S.SAIDATA FROM ITENSSAIDA I
JOIN PRODUTO P ON I.PROID=P.PROID
JOIN SAIDA S ON I.SAIID=S.SAIID