go 
create database TdsAlmoxarifado

go
use TdsAlmoxarifado

go 
--Select* from sys.tables
Create table AREA
( AREID int IDENTITY(1,1) PRIMARY KEY,
ARESDESCRICAO VARCHAR (100) NOT NULL)

CreatE table COLABORADOR
( COLID INT IDENTITY (1,1) PRIMARY KEY,
COLNOME VARCHAR(100) NOT NULL,
 COLCARGO VARCHAR(100) NULL,
  AREID INT, FOREIGN KEY (AREID) REFERENCES AREA(AREID)
  )

Create table PRODUTO
( PROID INT PRIMARY KEY IDENTITY,
PRODESCRICAO VARCHAR(100) NOT NULL,
PROMINIMO INT DEFAULT 0 CHECK (PROMINIMO>=0),
PROMAXIMO INT DEFAULT 0 CHECK (PROMAXIMO>=0),
PROESTOQUE INT DEFAULT 0 CHECK (PROESTOQUE>=0)
)

CREATE TABLE ENTRADA(
  ENTID INT PRIMARY KEY IDENTITY(1,1),
  ENTDATA DATETIME NOT NULL,
  ENTORIGEM VARCHAR(100) DEFAULT 'PADRAO' NULL,
  ENTNUMERONOTA VARCHAR(100) NULL,
  ENTOBSERVACAO VARCHAR(1000)
)

CREATE TABLE ITENSENTRADA(
  ITEID INT PRIMARY KEY IDENTITY(1,1),
  ITEQUANTIDADE INT NOT NULL CHECK (ITEQUANTIDADE>=0),
  ITEPRECO NUMERIC(18,2) CHECK (ITEPRECO>0)NOT NULL,
  ITETOTAL AS  ITEQUANTIDADE*ITEPRECO,
  ENTID INT NOT NULL,
  PROID INT NOT NULL,
  FOREIGN KEY (ENTID) REFERENCES ENTRADA(ENTID),
  FOREIGN KEY (PROID) REFERENCES PRODUTO(PROID)
  )