//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escola.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrupoCursoQuantidadeDisciplina
    {
        public int codigo { get; set; }
        public string descricao { get; set; }
        public string habilidade { get; set; }
        public string modalidade { get; set; }
        public Nullable<int> quantidade { get; set; }
    }
}
